# Exploration of the weather Dataset

### A countrywide dataset of 8.6 million weather events (2016 - 2022)

This repository contains a comprehensive collection of weather events data across 49 states in the United States. The dataset comprises a staggering 8.6 million events, ranging from regular occurrences like rain and snow to extreme weather phenomena such as storms and freezing conditions. The data spans from January 2016 to December 2022 and is sourced from 2,071 airport-based weather stations nationwide

In [15]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import plotly.express as px

In [16]:
df = pd.read_csv("WeatherEvents_Jan2016-Dec2022.csv")
df.head()

EventId  Type Severity       StartTime(UTC)         EndTime(UTC)  \
0     W-1  Snow    Light  2016-01-06 23:14:00  2016-01-07 00:34:00   
1     W-2  Snow    Light  2016-01-07 04:14:00  2016-01-07 04:54:00   
2     W-3  Snow    Light  2016-01-07 05:54:00  2016-01-07 15:34:00   
3     W-4  Snow    Light  2016-01-08 05:34:00  2016-01-08 05:54:00   
4     W-5  Snow    Light  2016-01-08 13:54:00  2016-01-08 15:54:00   

   Precipitation(in)     TimeZone AirportCode  LocationLat  LocationLng  \
0               0.00  US/Mountain        K04V      38.0972    -106.1689   
1               0.00  US/Mountain        K04V      38.0972    -106.1689   
2               0.03  US/Mountain        K04V      38.0972    -106.1689   
3               0.00  US/Mountain        K04V      38.0972    -106.1689   
4               0.00  US/Mountain        K04V      38.0972    -106.1689   

       City    County State  ZipCode  
0  Saguache  Saguache    CO  81149.0  
1  Saguache  Saguache    CO  81149.0  
2  Saguache  Saguache    CO  81149.0  
3  Saguache  Saguache    CO  81149.0  
4  Saguache  Saguache    CO  81149.0

In [17]:
# df.columns

In [18]:
df.isnull().sum()

EventId                  0
Type                     0
Severity                 0
StartTime(UTC)           0
EndTime(UTC)             0
Precipitation(in)        0
TimeZone                 0
AirportCode              0
LocationLat              0
LocationLng              0
City                 16912
County                   0
State                    0
ZipCode              69199
dtype: int64

In [19]:
df.dtypes

EventId               object
Type                  object
Severity              object
StartTime(UTC)        object
EndTime(UTC)          object
Precipitation(in)    float64
TimeZone              object
AirportCode           object
LocationLat          float64
LocationLng          float64
City                  object
County                object
State                 object
ZipCode              float64
dtype: object

In [20]:
df.describe()

Precipitation(in)   LocationLat   LocationLng       ZipCode
count       8.627181e+06  8.627181e+06  8.627181e+06  8.557982e+06
mean        9.287441e-02  3.878602e+01 -9.191172e+01  5.241150e+04
std         8.870326e-01  5.467708e+00  1.350340e+01  2.573249e+04
min         0.000000e+00  2.455710e+01 -1.245550e+02  1.022000e+03
25%         0.000000e+00  3.459950e+01 -9.782360e+01  3.121600e+04
50%         0.000000e+00  3.934510e+01 -8.977340e+01  5.391300e+04
75%         5.000000e-02  4.306220e+01 -8.194720e+01  7.350300e+04
max         1.104130e+03  4.894020e+01 -6.779280e+01  9.936200e+04

In [21]:
for c in df.columns:
    print(f"Feature: {c}")
    display(df[c].unique())

Feature: EventId


array(['W-1', 'W-2', 'W-3', ..., 'W-9091892', 'W-9091893', 'W-9091894'],
      shape=(8627181,), dtype=object)

Feature: Type


array(['Snow', 'Fog', 'Cold', 'Storm', 'Rain', 'Precipitation', 'Hail'],
      dtype=object)

Feature: Severity


array(['Light', 'Severe', 'Moderate', 'Heavy', 'UNK', 'Other'],
      dtype=object)

Feature: StartTime(UTC)


array(['2016-01-06 23:14:00', '2016-01-07 04:14:00',
       '2016-01-07 05:54:00', ..., '2019-03-29 09:13:00',
       '2019-03-29 20:17:00', '2019-03-29 20:33:00'],
      shape=(2285322,), dtype=object)

Feature: EndTime(UTC)


array(['2016-01-07 00:34:00', '2016-01-07 04:54:00',
       '2016-01-07 15:34:00', ..., '2019-02-22 06:18:00',
       '2019-03-07 03:09:00', '2019-03-29 20:17:00'],
      shape=(2237800,), dtype=object)

Feature: Precipitation(in)


array([0.000e+00, 3.000e-02, 1.000e-02, ..., 8.500e+00, 1.547e+01,
       2.125e+01], shape=(1755,))

Feature: TimeZone


array(['US/Mountain', 'US/Central', 'US/Eastern', 'US/Pacific'],
      dtype=object)

Feature: AirportCode


array(['K04V', 'KAXS', 'KAEL', ..., 'KB23', 'KARL', 'KBVR'],
      shape=(2071,), dtype=object)

Feature: LocationLat


array([38.0972, 34.6986, 43.6822, ..., 40.6   , 41.6   , 42.5833],
      shape=(2056,))

Feature: LocationLng


array([-106.1689,  -99.3381,  -93.3722, ..., -116.8667, -106.21  ,
       -108.2833], shape=(2063,))

Feature: City


array(['Saguache', 'Altus', 'Albert Lea', ..., 'Camdenton',
       'Battle Mountain', 'Rock River'], shape=(1717,), dtype=object)

Feature: County


array(['Saguache', 'Jackson', 'Freeborn', ..., 'Flagler', 'Rio Arriba',
       'Camden'], shape=(1100,), dtype=object)

Feature: State


array(['CO', 'OK', 'MN', 'LA', 'WI', 'ID', 'MI', 'KS', 'WY', 'MA', 'MO',
       'NM', 'NC', 'SC', 'RI', 'VA', 'CT', 'OR', 'ND', 'CA', 'NY', 'OH',
       'SD', 'AZ', 'NV', 'IA', 'TX', 'GA', 'NE', 'TN', 'AL', 'IL', 'AR',
       'WA', 'IN', 'UT', 'FL', 'WV', 'MS', 'PA', 'ME', 'MD', 'NJ', 'KY',
       'VT', 'MT', 'NH', 'DE'], dtype=object)

Feature: ZipCode


array([81149., 73521., 56007., ..., 65020., 89820., 82083.], shape=(2021,))

In [22]:
# Conteggio eventi per stato
state_counts = df['State'].value_counts().reset_index()
state_counts.columns = ['State', 'Count']

# Crea heatmap interattiva con plotly (USA choropleth)
fig = px.choropleth(
    state_counts,
    locations='State',
    locationmode='USA-states',
    color='Count',
    scope='usa',
    title='Heatmap Interattiva dei Disastri Meteo per Stato (2016-2022)',
    color_continuous_scale='Viridis',
    labels={'Count': 'Numero Disastri'}
)

fig.update_layout(
    geo=dict(
        projection_type='albers usa',
        showland=True,
        landcolor='rgb(243, 243, 243)'
    ),
    height=600,
    width=1000
)

fig.show()